openapi: 3.0.0
info:
  title: DMS backend service REST API
  version: '1.0'
  description: |
    REST API for the backend service.

    This is part of the mandatory exercise.

    For simplicity, [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) is not used
    although it is highly recommended in actual production scenarios.

    Diseño y Mantenimiento del Software.
    Grado en Ingeniería Informática, Universidad de Burgos, 2022-2023.
  contact:
    name: Universidad de Burgos
tags:
  - name: discussion
    description: Operations regarding the questions and answers.
  - name: moderation
    description: Moderation operations.
  - name: questions
    description: Question-related operations.
  - name: answers
    description: Answer-related operations.
  - name: comments
    description: Comment-related operations.
  - name: votes
    description: Vote-related operations.
  - name: reports
    description: Report-related operations.
  - name: server
    description: |
      Operations about the server itself (e.g., server status querying)
servers:
  - url: /api/v1
paths:
  '/':
    head:
      summary: Health test for the service
      description: |
        Use this operation to verify the server is running successfully and the
        API is reachable.
      operationId: dms2223backend.presentation.rest.server.health_test
      responses:
        '200':
          description: Mensaje "OK"
          content:
            'text/plain':
              schema:
                type: string
                example: 'OK'
      tags:
        - server
 